// Generated by CoffeeScript 1.3.3

chrome.browserAction.onClicked.addListener(function(tab) {
  chrome.tabs.sendMessage(tab.id, {
    action: "show"
  });
});

chrome.extension.onMessage.addListener(function(msg, sender, sendResponse) {
  console.log(msg);
  switch (msg.action) {
    case "queryTabs":
      chrome.tabs.query({
        title: "*" + msg.query + "*"
      }, function(tabs) {
        var queryInfo;
        queryInfo = {
          action: "queryResults",
          results: tabs
        };
        chrome.tabs.sendMessage(sender.tab.id, queryInfo);
      });
      break;
    case "activateTab":
      chrome.tabs.update(parseInt(msg.tabId, 10), {
        active: true
      }, function(tab) {});
  }
});
