// Generated by CoffeeScript 1.3.3

chrome.browserAction.onClicked.addListener(function(tab) {
  chrome.tabs.sendMessage(tab.id, {
    action: "toggle"
  });
});

chrome.extension.onMessage.addListener(function(msg, sender, sendResponse) {
  switch (msg.action) {
    case "queryTabs":
      chrome.tabs.query({}, function(tabs) {
        var pat, queryInfo, results, tab, _i, _len;
        results = [];
        for (_i = 0, _len = tabs.length; _i < _len; _i++) {
          tab = tabs[_i];
          pat = new RegExp(msg.query, 'i');
          if (pat.test(tab.url) || pat.test(tab.title)) {
            results.push(tab);
          }
        }
        queryInfo = {
          action: "queryResults",
          results: results
        };
        chrome.tabs.sendMessage(sender.tab.id, queryInfo);
      });
      break;
    case "activateTab":
      chrome.tabs.update(parseInt(msg.tabId, 10), {
        active: true
      }, function(tab) {});
  }
});
