// Generated by CoffeeScript 1.3.3
var $tabswitch, $tsInput, $tsResults;

$tabswitch = $("<div id=\"tabswitch\"><input type=\"text\"><ul></ul></div>");

$("body").append($tabswitch);

$tsInput = $("input[type=text]", $tabswitch);

$tsInput.on("keyup", function(e) {
  var $active, $next, $prev, query, selectedTabId;
  $active = $("li.active", $tsResults);
  switch (e.keyCode) {
    case 13:
      selectedTabId = $("li.active", $tsResults).attr("id");
      if (selectedTabId) {
        chrome.extension.sendMessage({
          action: "activateTab",
          tabId: selectedTabId
        });
        $tabswitch.hide();
      }
      break;
    case 27:
      $tabswitch.hide();
      break;
    case 38:
      $prev = $active.prev("li");
      if ($prev.size()) {
        $active.removeClass("active");
        $prev.addClass("active");
      }
      break;
    case 40:
      $next = $active.next("li");
      if ($next.size()) {
        $active.removeClass("active");
        $next.addClass("active");
      }
      break;
    default:
      query = $tsInput.val();
      if (query.length > 0) {
        chrome.extension.sendMessage({
          action: "queryTabs",
          query: query
        });
      } else {
        $tsResults.empty();
      }
  }
});

$tsResults = $("ul", $tabswitch);

chrome.extension.onMessage.addListener(function(msg) {
  var $result, maxResults, results, tab, _i, _len, _ref;
  switch (msg.action) {
    case "toggle":
      $tabswitch.toggle();
      $tsInput.select();
      break;
    case "queryResults":
      maxResults = 5;
      results = 0;
      $tsResults.empty();
      _ref = msg.results;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        tab = _ref[_i];
        $result = $("<li id=\"" + tab.id + "\">\n    <h2>" + tab.title + "</h2>\n    <span>" + tab.url + "</span>\n</li>");
        if (tab.favIconUrl) {
          $result.prepend($("<img src=\"" + tab.favIconUrl + "\">"));
        }
        $tsResults.append($result);
        if (++results >= maxResults) {
          break;
        }
      }
      $("li:first-child", $tsResults).addClass("active");
  }
});
