// Generated by CoffeeScript 1.3.3
var $tabswitch, $tsInput, $tsResults;

$tabswitch = $("<div id=\"tabswitch\"><input type=\"text\"><ul></ul></div>");

$("body").append($tabswitch);

$tsInput = $("input[type=text]", $tabswitch);

$tsInput.on("keyup", function(e) {
  var query, selectedTabId;
  if (e.keyCode === 13) {
    selectedTabId = $("li:first-child", $tsResults).attr("id");
    if (selectedTabId) {
      chrome.extension.sendMessage({
        action: "activateTab",
        tabId: selectedTabId
      });
      $tabswitch.hide();
    }
  } else {
    query = $tsInput.val();
    if (query.length > 0) {
      chrome.extension.sendMessage({
        action: "queryTabs",
        query: query
      });
    } else {
      $tsResults.empty();
    }
  }
});

$tsResults = $("ul", $tabswitch);

chrome.extension.onMessage.addListener(function(msg) {
  var $result, maxResults, results, tab, _i, _len, _ref;
  switch (msg.action) {
    case "show":
      $tabswitch.show();
      $tsInput.select();
      break;
    case "queryResults":
      maxResults = 5;
      results = 0;
      $tsResults.empty();
      _ref = msg.results;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        tab = _ref[_i];
        $result = $("<li id=\"" + tab.id + "\">\n    <h2>" + tab.title + "</h2>\n    <span>" + tab.url + "</span>\n</li>");
        if (tab.favIconUrl) {
          $result.prepend($("<img src=\"" + tab.favIconUrl + "\">"));
        }
        $tsResults.append($result);
        if (++results >= maxResults) {
          break;
        }
      }
  }
});
